"""
This type stub file was generated by pyright.
"""

class ArParser:
    """
    Class contains all information obtained by ar command.
    """
    def __init__(self, pkgfile_path) -> None:
        ...

    def parse(self) -> None:
        ...



