"""
This type stub file was generated by pyright.
"""

import sys

if hasattr(sys.stdout, 'isatty') and sys.stdout.isatty():
    class Color:
        """
        Colors used when doing printouts with rpmlint
        """
        Bold = ...
        Red = ...
        Yellow = ...
        Reset = ...


else:
    class Color:
        """
        Colors used when doing printouts with rpmlint
        """
        Bold = ...
        Red = ...
        Yellow = ...
        Reset = ...


