"""
This type stub file was generated by pyright.
"""

class Config:
    """
    Load and parse rpmlint configuration.

    Configuration files are written in toml and should be placed in one of
    the XDG_CONFIG_DIRS directory or passed as "config" argument directly.

    By default it loads configdefaults.toml and all default locations and
    initializes basic testing layout for the rpmlint binary. Based on the
    opening order 'newer' configuration takes precedence over already
    existing one.
    """
    re_filter = ...
    re_badness = ...
    config_defaults = ...
    def __init__(self, config=...) -> None:
        """
        Initialize basic options and load rpmlint configuration.

        Args:
            config: A list of paths of configuration file(s) passed by user in
            command line.
        """
        ...
    
    def find_configs(self, config=...) -> None:
        """
        Find and store paths to all config files.

        It searches for default configuration, files in XDG_CONFIG_DIRS and
        user defined configuration (argument "config"). All configuration
        file paths found are then stored in self.conf_files variable.
        XDG_CONFIG_DIRS contains preference-ordered set of base directories
        to search for configuration files. Users can override it by their
        own configuration file (config parameter) and then that is
        added too.
        """
        ...
    
    def load_config(self, config=...) -> None:
        """
        Load the configuration files and append it to local dictionary.

        It's stored in self.configuration with the content of already loaded
        options.
        """
        ...
    
    def load_rpmlintrc(self, rpmlintrc_file) -> None:
        """
        Load existing rpmlintrc files.

        Only setBadness and addFilter are processed.
        """
        ...
    
    def print_config(self) -> None:
        """Print the current state of the configuration."""
        ...
    
    def set_badness(self, result, badness) -> None:
        """Set specific badness for some result."""
        ...
    


