"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager

ENGLISH_ENVIRONMENT = ...
def string_center(message, filler=...) -> str:
    """
    Create string centered of the terminal
    """
    ...

def print_centered(message, filler=...) -> None:
    """
    Print message in the center of a terminal
    """
    ...

def print_warning(message) -> None:
    """
    Print warning message to stderr.
    """
    ...

def byte_to_string(item) -> str | list[str | list[Any] | Any | None] | None:
    """
    Convert byte items to strings
    """
    ...

def readlines(path) -> Generator[str | list[str | list[Any] | Any | None] | Any | None, Any, None]:
    ...

@contextmanager
def pushd(new_dir) -> Generator[None, Any, None]:
    """
    Mimics Unix pushd/popd
    """
    ...

