"""
This type stub file was generated by pyright.
"""

class LddParser:
    """
    Class contains all information obtained by ldd command
    about undefined symbols and unused direct dependencies.

    Parse these 2 outputs:

    $ ldd -u libnss-unused-dependency.so
    Unused direct dependencies:
        /lib/libnss_files.so.2

    $ ldd -r libthread-undefined-symbol.so
        linux-gate.so.1 (0xf7fce000)
        libc.so.6 => /lib/libc.so.6 (0xf7d9a000)
        /lib/ld-linux.so.2 (0xf7fcf000)
    undefined symbol: ps_pdwrite	(./libthread-undefined-symbol.so)
    undefined symbol: ps_pglobal_lookup	(./libthread-undefined-symbol.so)
    undefined symbol: ps_lsetregs	(./libthread-undefined-symbol.so)
    undefined symbol: ps_getpid	(./libthread-undefined-symbol.so)
    undefined symbol: ps_lgetfpregs	(./libthread-undefined-symbol.so)
    undefined symbol: ps_lsetfpregs	(./libthread-undefined-symbol.so)
    undefined symbol: ps_lgetregs	(./libthread-undefined-symbol.so)
    undefined symbol: ps_pdread	(./libthread-undefined-symbol.so)
    undefined symbol: gss_release_cred, version gssapi_krb5_2_MIT	(./test/ldd/libtirpc.so.3.0.0)
    undefined symbol: gss_canonicalize_name, version gssapi_krb5_2_MIT	(./test/ldd/libtirpc.so.3.0.0)
    undefined symbol: gss_pname_to_uid, version gssapi_krb5_2_MIT	(./test/ldd/libtirpc.so.3.0.0)
    undefined symbol: gss_accept_sec_context, version gssapi_krb5_2_MIT	(./test/ldd/libtirpc.so.3.0.0)
    undefined symbol: gss_verify_mic, version gssapi_krb5_2_MIT	(./test/ldd/libtirpc.so.3.0.0)
    undefined symbol: gss_get_mic, version gssapi_krb5_2_MIT	(./test/ldd/libtirpc.so.3.0.0)
    """
    unused_regex = ...
    undef_regex = ...
    def __init__(self, pkgfile_path, path, is_installed_pkg) -> None:
        ...

    def parse_dependencies(self) -> None:
        ...

    def parse_undefined_symbols(self) -> None:
        ...



