"""
This type stub file was generated by pyright.
"""

class ObjdumpParser:
    """
    Class contains all information obtained by objdump command. Right now, we
    are interested in DW_TAG_compile_unit of debug info.

    Example output of objdump:

    <0><b>: Abbrev Number: 1 (DW_TAG_compile_unit)
       <c>   DW_AT_stmt_list   : 0x0
       <10>   DW_AT_low_pc      : 0x927840
       <18>   DW_AT_high_pc     : 0x92786b
       <20>   DW_AT_name        : (indirect string, offset: 0x0): ../sysdeps/x86_64/start.S
       <24>   DW_AT_comp_dir    : (indirect string, offset: 0x1a): /home/abuild/rpmbuild/BUILD/glibc-2.31/csu
       <28>   DW_AT_producer    : (indirect string, offset: 0x45): GNU AS 2.33.1
       <2c>   DW_AT_language    : 32769    (MIPS assembler)
     Compilation Unit @ offset 0x2e:
      Length:        0x3c (32-bit)
    """
    dw_at_prefix = ...
    def __init__(self, pkgfile_path, path) -> None:
        ...
    
    def parse_dwarf_compilation_units(self) -> None:
        ...
    


