"""
This type stub file was generated by pyright.
"""

has_magic = ...
DepInfo = ...
PREREQ_FLAG = ...
SCRIPT_TAGS = ...
RPM_SCRIPTLETS = ...
gzip_regex = ...
bz2_regex = ...
xz_regex = ...
zst_regex = ...
def catcmd(fname) -> Literal['bzip2 -dcf', 'xz -dc', 'zstd -dc', 'gzip -dcf']:
    """Get a 'cat' command that handles possibly compressed files."""
    ...

def compression_algorithm(fname) -> Any | None:
    """Return compression algorithm based on filename if known, None otherwise."""
    ...

def is_utf8(fname) -> bool:
    ...

def is_utf8_bytestr(s) -> bool:
    """Returns True whether the given text is UTF-8.
    Due to changes in rpm, needs to handle both bytes and unicode."""
    ...

def has_forbidden_controlchars(val) -> str | bytes | Literal[False]:
    ...

def compareEVR(evr1, evr2):
    ...

def rangeCompare(reqtuple, provtuple):
    """returns true if provtuple satisfies reqtuple"""
    ...

def formatRequire(name, flags, evr) -> str:
    ...

def versionToString(evr) -> str:
    ...

def stringToVersion(verstring) -> tuple[None, None, None] | tuple[int | None, Any | None, Any | None]:
    ...

def parse_deps(line) -> list[Any]:
    """
    Parse provides/requires/conflicts/obsoletes line to list of
    (name, flags, (epoch, version, release)) tuples.
    """
    ...

def get_magic(path) -> Literal['']:
    ...

class AbstractPkg:
    def cleanup(self) -> None:
        ...

    def scriptprog(self, which) -> LiteralString | Literal['']:
        """
        Get the specified script interpreter as a string.
        Depending on rpm-python version, the string may or may not include
        interpreter arguments, if any.
        """
        ...

    def __enter__(self) -> Self:
        ...

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        ...

    def check_versioned_dep(self, name, version) -> bool:
        ...

    def read_with_mmap(self, filename) -> str:
        """Mmap a file, return it's content decoded."""
        ...

    def grep(self, regex, filename) -> int | None:
        """Grep regex from a file, return first matching line number (starting with 1)."""
        ...



class Pkg(AbstractPkg):
    _magic_from_compressed_re = ...
    def __init__(self, filename, dirname, header=..., is_source=..., extracted=..., verbose=...) -> None:
        ...

    @property
    def is_no_source(self) -> list[Any] | Literal[False]:
        ...

    def __getitem__(self, key) -> str | list[str | list[Any] | Any | None] | None:
        ...

    def dir_name(self) -> str:
        ...

    def check_signature(self) -> tuple[int, str]:
        ...

    def cleanup(self) -> None:
        ...

    def langtag(self, tag, lang) -> str | list[str | list[Any] | Any | None] | None:
        """Get value of tag in the given language."""
        ...

    def readlink(self, pkgfile) -> None:
        """
        Resolve symlinks for the given PkgFile, return the dereferenced
        PkgFile if it is found in this package, None if not.
        """
        ...

    def get_core_reqs(self) -> list[Any]:
        """
        Return the list of dependencies that are not found by find-requires
        withouth the flag RPM
        """
        ...



def get_installed_pkgs(name) -> list[Any]:
    """Get list of installed package objects by name."""
    ...

class InstalledPkg(Pkg):
    def __init__(self, name, hdr=...) -> None:
        ...

    def cleanup(self) -> None:
        ...

    def check_signature(self) -> tuple[Literal[0], Literal['fake: pgp md5 OK']]:
        ...



class FakeHeader(dict):
    def sprintf(self, expr):
        """
        Replaces expressions like %{} with actual package
        """
        ...

    def __missing__(self, key):
        ...



class FakePkg(AbstractPkg):
    _autoheaders = ...
    def __init__(self, name, is_source=...) -> None:
        ...

    def add_file(self, path, name) -> PkgFile:
        ...

    def create_files(self, files) -> None:
        """
        This is a helper method to create files(real files); not PkgFile
        objects.
        """
        ...

    def add_dir(self, path, metadata=...) -> PkgFile:
        ...

    def add_file_with_content(self, name, content, metadata=..., **flags) -> None:
        """
        Add file to the FakePkg and fill the file with provided
        string content.
        """
        ...

    def initiate_files_base_data(self) -> None:
        """ This method is called after adding metadata of each file """
        ...

    def add_header(self, header) -> None:
        ...

    def add_symlink_to(self, name, target) -> None:
        """
        Add symlink to name file which path is related to name.
        Eg. name == '/etc/foo' and target == '../bar' creates a symlink file
        /etc/bar that points to /etc/foo.
        """
        ...

    def readlink(self, pkgfile) -> None:
        ...

    def dir_name(self) -> str:
        ...

    def md5_checksum(self, file_name) -> str:
        ...

    def cleanup(self) -> None:
        ...

    def get_core_reqs(self) -> list[Any]:
        ...

    def __getitem__(self, key) -> None:
        ...



