"""
This type stub file was generated by pyright.
"""

ENCHANT = ...
class Spellcheck:
    """
    The object containing current state of spellchecking used within rpmlint
    """
    sentence_break_regex = ...
    _enchant_checkers = ...
    def __init__(self) -> None:
        ...
    
    def spell_check(self, text, fmt, lang=..., pkgname=..., ignored_words=...) -> dict[Any, Any] | None:
        """
        Spell check string and return list of warnings if we found out any typos.
        text: the checked text
        fmt: format of the result ie 'Description({})'
        lang: language code ie en_US, default en_US
        pkgname: name of the checked package - for specific ignore finegraining
        ignored_words: words to be ignored by the spellchecker
        """
        ...
    


