"""
This type stub file was generated by pyright.
"""

class StringsParser:
    """
    Class contains all information obtained by strings command.
    """
    def __init__(self, pkgfile_path) -> None:
        ...
    
    def parse(self) -> None:
        ...
    


