name: 'Package RPM'
description: 'Build and package RPMs from spec file'
author: 'Aura Herrero Ruiz'

inputs:
  spec_file:
    description: 'Path of the spec file to build'
    required: true
  sources_dir:
    description: 'Path of files to copy to "SOURCES" on the rpmbuild directory'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'package'
  color: 'red'

