on: [push, workflow_dispatch]

jobs:
  testjob:
    runs-on: ubuntu-latest
    name: Test Package RPM
    steps:
      - name: Checkout action repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Prepare test source
        run: cd test && tar -cf SOURCES/test-rpm.tar test-rpm.c
      - name: Test action
        id: build
        uses: ./
        with:
          spec_file: test/test.spec
          sources_dir: test/SOURCES
      - name: Upload test artifacts
        uses: actions/upload-artifact@v7
        with:
          name: test-built-package
          path: |
            ${{steps.build.outputs.rpm_directory_path}}
            ${{steps.build.outputs.source_rpm_directory_path}}
